name: Django

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Build Step
        run: echo "This is a build step"

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Test Step
        run: echo "This is a test step"

  integration:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Integration Step
        run: echo "This is an integration step"

  artifact:
    runs-on: ubuntu-20.04
    needs: integration
    steps:
      - name: Create Artifact
        run: echo "hello" > hello.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: hello.txt
